# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('run_id', models.CharField(max_length=32)),
                ('run_data', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
