# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0003_visitor_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('run_id', models.CharField(max_length=32)),
                ('run_data', models.TextField()),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.Visit')),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
