# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0002_event_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
